### PR TITLE
Update simon-db.md

### PR DESCRIPTION
**Pull request by Jtrom314**
Hi Professor Jensen,

I had a problem with getting access to my Mongo DB on my startup and simon server. After working with a TA, we came up with the following solution. I don't know if it belongs here but I think it could help others if they had the same problem that I did

### CODE REVIEW

**Review by leesjensen — COMMENTED** [review]
Hum, that seems like a pretty heavy hammer. Do you know what was actually the problem? Was it really PM2, or was it restarting the service that fixed the problem? You did several things there, including updating the running process to reset their environment. I thought you had your database running several weeks ago.

**Comment by Jtrom314** [comment]
Yeah,

I did have the database working weeks ago, however, when I pushed my
startup to the server, it somehow reverted those changes that we made
together and the server changed the environment variables to be the one
that you had set. (ie, I was getting your data again both in simon and in
the startup).

I think it was PM2 because the server connection worked on both my local
machine and on the web server when I stopped PM2 and ran node index.js on
the service (while ssh'ed on the server)

We tried restarting the service but for some reason it only worked when we
essentially deleted the service from PM2 and put it back on and
re-assigning the port

I hope that made sense. I can come into office hours on Monday and talk
about it some more with you if needed.

Jacob

**Comment by leesjensen** [comment]
I'm guessing the problem was that we didn't run `pm2 save` after we reset the services to use the new environment. Another student reported this problem and I updated the docs to reflect this. So unless you think there is something still outstanding I would like to close the pull request.

**Comment by Jtrom314** [comment]
Sounds good!

**Comment by leesjensen** [comment]
Resolved with other additions to the instruction. Specifically (455e89bd35e5d8919f39e2da897a89382add2478):

You then need to tell your Simon and Start Up services to use the new values found in the environment file. To do this you need to tell our service daemon, PM2, to reload its stored environment for all services that it manages. You then need to tell PM2 to save the new configuration so that it will persist when your server restarts. Run these commands from a SSH session on your production server.

```sh
pm2 restart all --update-env
pm2 save
```

**Pull request closed without merging**
